
/*------------------------------------------------------------------------
    File        : iDisposable
    Purpose     :
    Syntax      :
    Description :
    Author(s)   : Andriuhan
    Created     : Wed Apr 04 09:34:43 EEST 2012
    Notes       :
  ----------------------------------------------------------------------*/

using Progress.Lang.*.

interface com.quarix.base.iDisposable:

end interface.