class wicketds.server.tableobjects.ttcustomer final:

    define public static property rowid as character no-undo initial "rowid"
        get.
        private set.

    define public static property rowstate as character no-undo initial "rowstate"
        get.
        private set.

    define public static property SortOrder as character no-undo initial "SortOrder"
        get.
        private set.

    define public static property Address as character no-undo initial "Address"
        get.
        private set.

    define public static property Address2 as character no-undo initial "Address2"
        get.
        private set.

    define public static property Balance as character no-undo initial "Balance"
        get.
        private set.

    define public static property City as character no-undo initial "City"
        get.
        private set.

    define public static property Comments as character no-undo initial "Comments"
        get.
        private set.

    define public static property Contact as character no-undo initial "Contact"
        get.
        private set.

    define public static property Country as character no-undo initial "Country"
        get.
        private set.

    define public static property CreditLimit as character no-undo initial "CreditLimit"
        get.
        private set.

    define public static property CustNum as character no-undo initial "CustNum"
        get.
        private set.

    define public static property Discount as character no-undo initial "Discount"
        get.
        private set.

    define public static property EmailAddress as character no-undo initial "EmailAddress"
        get.
        private set.

    define public static property Fax as character no-undo initial "Fax"
        get.
        private set.

    define public static property Name as character no-undo initial "Name"
        get.
        private set.

    define public static property Phone as character no-undo initial "Phone"
        get.
        private set.

    define public static property PostalCode as character no-undo initial "PostalCode"
        get.
        private set.

    define public static property SalesRep as character no-undo initial "SalesRep"
        get.
        private set.

    define public static property State as character no-undo initial "State"
        get.
        private set.

    define public static property Terms as character no-undo initial "Terms"
        get.
        private set.

    define public static property StateName as character no-undo initial "StateName"
        get.
        private set.

    define public static property SalesRepName as character no-undo initial "SalesRepName"
        get.
        private set.
end class.
