class wicketds.server.tableobjects.ttcustomeridlist final:

    define public static property IdListOrder as character no-undo initial "IdListOrder"
        get.
        private set.

    define public static property HashCode as character no-undo initial "HashCode"
        get.
        private set.

    define public static property CustNum as character no-undo initial "CustNum"
        get.
        private set.
end class.
