class wicketds.server.tableobjects.ttitem final:

    define public static property rowid as character no-undo initial "rowid"
        get.
        private set.

    define public static property rowstate as character no-undo initial "rowstate"
        get.
        private set.

    define public static property SortOrder as character no-undo initial "SortOrder"
        get.
        private set.

    define public static property CatDescription as character no-undo initial "CatDescription"
        get.
        private set.

    define public static property ItemName as character no-undo initial "ItemName"
        get.
        private set.

    define public static property Itemnum as character no-undo initial "Itemnum"
        get.
        private set.

    define public static property Price as character no-undo initial "Price"
        get.
        private set.

    define public static property Weight as character no-undo initial "Weight"
        get.
        private set.

    define public static property Category1 as character no-undo initial "Category1"
        get.
        private set.

    define public static property Category2 as character no-undo initial "Category2"
        get.
        private set.
end class.
