class wicketds.server.tableobjects.ttorder final:

    define public static property rowid as character no-undo initial "rowid"
        get.
        private set.

    define public static property rowstate as character no-undo initial "rowstate"
        get.
        private set.

    define public static property SortOrder as character no-undo initial "SortOrder"
        get.
        private set.

    define public static property BillToID as character no-undo initial "BillToID"
        get.
        private set.

    define public static property Carrier as character no-undo initial "Carrier"
        get.
        private set.

    define public static property CreditCard as character no-undo initial "CreditCard"
        get.
        private set.

    define public static property CustNum as character no-undo initial "CustNum"
        get.
        private set.

    define public static property Instructions as character no-undo initial "Instructions"
        get.
        private set.

    define public static property OrderDate as character no-undo initial "OrderDate"
        get.
        private set.

    define public static property Ordernum as character no-undo initial "Ordernum"
        get.
        private set.

    define public static property OrderStatus as character no-undo initial "OrderStatus"
        get.
        private set.

    define public static property PO as character no-undo initial "PO"
        get.
        private set.

    define public static property PromiseDate as character no-undo initial "PromiseDate"
        get.
        private set.

    define public static property SalesRep as character no-undo initial "SalesRep"
        get.
        private set.

    define public static property ShipDate as character no-undo initial "ShipDate"
        get.
        private set.

    define public static property ShipToID as character no-undo initial "ShipToID"
        get.
        private set.

    define public static property Terms as character no-undo initial "Terms"
        get.
        private set.

    define public static property WarehouseNum as character no-undo initial "WarehouseNum"
        get.
        private set.

    define public static property CustName as character no-undo initial "CustName"
        get.
        private set.

    define public static property SalesRepName as character no-undo initial "SalesRepName"
        get.
        private set.
end class.
