class wicketds.server.tableobjects.ttstateidlist final:

    define public static property IdListOrder as character no-undo initial "IdListOrder"
        get.
        private set.

    define public static property HashCode as character no-undo initial "HashCode"
        get.
        private set.

    define public static property StateCode as character no-undo initial "StateCode"
        get.
        private set.
end class.
