class wicketds.server.tableobjects.ttstate final:

    define public static property rowid as character no-undo initial "rowid"
        get.
        private set.

    define public static property rowstate as character no-undo initial "rowstate"
        get.
        private set.

    define public static property SortOrder as character no-undo initial "SortOrder"
        get.
        private set.

    define public static property Region as character no-undo initial "Region"
        get.
        private set.

    define public static property StateCode as character no-undo initial "StateCode"
        get.
        private set.

    define public static property StateName as character no-undo initial "StateName"
        get.
        private set.
end class.
