class wicketds.server.tableobjects.ttdepartment final:

    define public static property rowid as character no-undo initial "rowid"
        get.
        private set.

    define public static property rowstate as character no-undo initial "rowstate"
        get.
        private set.

    define public static property SortOrder as character no-undo initial "SortOrder"
        get.
        private set.

    define public static property DeptCode as character no-undo initial "DeptCode"
        get.
        private set.

    define public static property DeptName as character no-undo initial "DeptName"
        get.
        private set.
end class.
