class wicketds.server.tableobjects.ttdepartmentidlist final:

    define public static property IdListOrder as character no-undo initial "IdListOrder"
        get.
        private set.

    define public static property HashCode as character no-undo initial "HashCode"
        get.
        private set.

    define public static property DeptCode as character no-undo initial "DeptCode"
        get.
        private set.
end class.
