class wicketds.server.tableobjects.ttemployee final:

    define public static property rowid as character no-undo initial "rowid"
        get.
        private set.

    define public static property rowstate as character no-undo initial "rowstate"
        get.
        private set.

    define public static property SortOrder as character no-undo initial "SortOrder"
        get.
        private set.

    define public static property EmpNum as character no-undo initial "EmpNum"
        get.
        private set.

    define public static property Address as character no-undo initial "Address"
        get.
        private set.

    define public static property Address2 as character no-undo initial "Address2"
        get.
        private set.

    define public static property Birthdate as character no-undo initial "Birthdate"
        get.
        private set.

    define public static property City as character no-undo initial "City"
        get.
        private set.

    define public static property DeptCode as character no-undo initial "DeptCode"
        get.
        private set.

    define public static property FirstName as character no-undo initial "FirstName"
        get.
        private set.

    define public static property LastName as character no-undo initial "LastName"
        get.
        private set.

    define public static property HomePhone as character no-undo initial "HomePhone"
        get.
        private set.

    define public static property WorkPhone as character no-undo initial "WorkPhone"
        get.
        private set.

    define public static property Position as character no-undo initial "Position"
        get.
        private set.

    define public static property StartDate as character no-undo initial "StartDate"
        get.
        private set.

    define public static property PostalCode as character no-undo initial "PostalCode"
        get.
        private set.

    define public static property State as character no-undo initial "State"
        get.
        private set.

    define public static property DeptName as character no-undo initial "DeptName"
        get.
        private set.

    define public static property StateName as character no-undo initial "StateName"
        get.
        private set.
end class.
