class wicketds.server.tableobjects.ttitemidlist final:

    define public static property IdListOrder as character no-undo initial "IdListOrder"
        get.
        private set.

    define public static property HashCode as character no-undo initial "HashCode"
        get.
        private set.

    define public static property Itemnum as character no-undo initial "Itemnum"
        get.
        private set.
end class.
