class wicketds.server.tableobjects.ttorderline final:

    define public static property rowid as character no-undo initial "rowid"
        get.
        private set.

    define public static property rowstate as character no-undo initial "rowstate"
        get.
        private set.

    define public static property SortOrder as character no-undo initial "SortOrder"
        get.
        private set.

    define public static property Discount as character no-undo initial "Discount"
        get.
        private set.

    define public static property ExtendedPrice as character no-undo initial "ExtendedPrice"
        get.
        private set.

    define public static property Itemnum as character no-undo initial "Itemnum"
        get.
        private set.

    define public static property Linenum as character no-undo initial "Linenum"
        get.
        private set.

    define public static property OrderLineStatus as character no-undo initial "OrderLineStatus"
        get.
        private set.

    define public static property Ordernum as character no-undo initial "Ordernum"
        get.
        private set.

    define public static property Price as character no-undo initial "Price"
        get.
        private set.

    define public static property Qty as character no-undo initial "Qty"
        get.
        private set.

    define public static property ItemName as character no-undo initial "ItemName"
        get.
        private set.
end class.
