class wicketds.server.tableobjects.ttorderidlist final:

    define public static property IdListOrder as character no-undo initial "IdListOrder"
        get.
        private set.

    define public static property HashCode as character no-undo initial "HashCode"
        get.
        private set.

    define public static property Ordernum as character no-undo initial "Ordernum"
        get.
        private set.
end class.
