class wicketds.server.tableobjects.ttpurchaseorder final:

    define public static property rowid as character no-undo initial "rowid"
        get.
        private set.

    define public static property rowstate as character no-undo initial "rowstate"
        get.
        private set.

    define public static property SortOrder as character no-undo initial "SortOrder"
        get.
        private set.

    define public static property PONum as character no-undo initial "PONum"
        get.
        private set.

    define public static property DateEntered as character no-undo initial "DateEntered"
        get.
        private set.

    define public static property ReceiveDate as character no-undo initial "ReceiveDate"
        get.
        private set.

    define public static property POStatus as character no-undo initial "POStatus"
        get.
        private set.

    define public static property SupplierIDNum as character no-undo initial "SupplierIDNum"
        get.
        private set.
end class.
