class wicketds.server.tableobjects.ttsalesrep final:

    define public static property rowid as character no-undo initial "rowid"
        get.
        private set.

    define public static property rowstate as character no-undo initial "rowstate"
        get.
        private set.

    define public static property SortOrder as character no-undo initial "SortOrder"
        get.
        private set.

    define public static property SalesRep as character no-undo initial "SalesRep"
        get.
        private set.

    define public static property RepName as character no-undo initial "RepName"
        get.
        private set.

    define public static property Region as character no-undo initial "Region"
        get.
        private set.
end class.
