 
 /*------------------------------------------------------------------------
    File        : DataType
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : Andrei
    Created     : Tue May 21 09:56:20 EEST 2013
    Notes       : 
  ----------------------------------------------------------------------*/

USING Progress.Lang.*.

ROUTINE-LEVEL ON ERROR UNDO, THROW.

CLASS com.mrg.framework.util.DataType:
     

END CLASS.